# Generated by Django 5.2.4 on 2025-07-15 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DHLAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('account_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_validated', models.DateTimeField(blank=True, null=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pendiente'), ('valid', 'Válida'), ('invalid', 'Inválida')], default='pending', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta DHL',
                'verbose_name_plural': 'Cuentas DHL',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RateQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_postal_code', models.CharField(max_length=20)),
                ('origin_city', models.CharField(max_length=50)),
                ('origin_country', models.CharField(max_length=2)),
                ('origin_state', models.CharField(blank=True, max_length=50)),
                ('destination_postal_code', models.CharField(max_length=20)),
                ('destination_city', models.CharField(max_length=50)),
                ('destination_country', models.CharField(max_length=2)),
                ('destination_state', models.CharField(blank=True, max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('length', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width', models.DecimalField(decimal_places=2, max_digits=8)),
                ('height', models.DecimalField(decimal_places=2, max_digits=8)),
                ('service_name', models.CharField(max_length=100)),
                ('service_code', models.CharField(max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('delivery_time', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('created', 'Creado'), ('in_transit', 'En Tránsito'), ('delivered', 'Entregado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('service_type', models.CharField(choices=[('P', 'DHL Express Worldwide'), ('K', 'DHL Express 9:00'), ('U', 'DHL Express 10:30'), ('Y', 'DHL Express 12:00')], default='P', max_length=1)),
                ('payment_type', models.CharField(choices=[('S', 'Remitente'), ('R', 'Destinatario'), ('T', 'Tercero')], default='S', max_length=1)),
                ('shipper_name', models.CharField(max_length=100)),
                ('shipper_company', models.CharField(blank=True, max_length=100)),
                ('shipper_phone', models.CharField(max_length=20)),
                ('shipper_email', models.EmailField(max_length=254)),
                ('shipper_address', models.TextField()),
                ('shipper_city', models.CharField(max_length=50)),
                ('shipper_state', models.CharField(blank=True, max_length=50)),
                ('shipper_postal_code', models.CharField(max_length=20)),
                ('shipper_country', models.CharField(max_length=2)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_company', models.CharField(blank=True, max_length=100)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_address', models.TextField()),
                ('recipient_city', models.CharField(max_length=50)),
                ('recipient_state', models.CharField(blank=True, max_length=50)),
                ('recipient_postal_code', models.CharField(max_length=20)),
                ('recipient_country', models.CharField(max_length=2)),
                ('package_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('package_length', models.DecimalField(decimal_places=2, max_digits=8)),
                ('package_width', models.DecimalField(decimal_places=2, max_digits=8)),
                ('package_height', models.DecimalField(decimal_places=2, max_digits=8)),
                ('package_description', models.TextField()),
                ('package_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_currency', models.CharField(default='USD', max_length=3)),
                ('estimated_delivery', models.CharField(blank=True, max_length=50)),
                ('cost', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EPODDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=50)),
                ('pdf_data', models.TextField()),
                ('file_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epod_documents', to='dhl_api.shipment')),
            ],
            options={
                'verbose_name': 'Documento ePOD',
                'verbose_name_plural': 'Documentos ePOD',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='dhl_api.shipment')),
            ],
            options={
                'verbose_name': 'Evento de Seguimiento',
                'verbose_name_plural': 'Eventos de Seguimiento',
                'ordering': ['-timestamp'],
            },
        ),
    ]
