# Generated by Django 4.2.7 on 2025-07-26 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dhl_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandedCostQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin_postal_code', models.CharField(max_length=20)),
                ('origin_city', models.CharField(max_length=100)),
                ('origin_country', models.CharField(max_length=2)),
                ('destination_postal_code', models.CharField(max_length=20)),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_country', models.CharField(max_length=2)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('shipment_purpose', models.CharField(choices=[('commercial', 'Comercial'), ('personal', 'Personal')], default='personal', max_length=20)),
                ('transportation_mode', models.CharField(choices=[('air', 'Aéreo'), ('ocean', 'Marítimo'), ('ground', 'Terrestre')], default='air', max_length=20)),
                ('is_customs_declarable', models.BooleanField(default=True)),
                ('is_dtp_requested', models.BooleanField(default=False)),
                ('is_insurance_requested', models.BooleanField(default=False)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('duties_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxes_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fees_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('items_count', models.PositiveIntegerField(default=1)),
                ('total_declared_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('warnings_count', models.PositiveIntegerField(default=0)),
                ('full_response', models.JSONField(blank=True, help_text='Respuesta completa de DHL API', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landed_cost_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotización Landed Cost',
                'verbose_name_plural': 'Cotizaciones Landed Cost',
                'ordering': ['-created_at'],
            },
        ),
    ]
