# Generated by Django 4.2.7 on 2025-08-03 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dhl_api', '0002_landedcostquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('create_shipment', 'Crear envío'), ('view_shipment', 'Ver envío'), ('edit_shipment', 'Editar envío'), ('delete_shipment', 'Eliminar envío'), ('track_shipment', 'Rastrear envío'), ('get_rate', 'Obtener cotización'), ('compare_rates', 'Comparar cotizaciones'), ('create_account', 'Crear cuenta DHL'), ('edit_account', 'Editar cuenta DHL'), ('delete_account', 'Eliminar cuenta DHL'), ('set_default_account', 'Establecer cuenta por defecto'), ('landed_cost_quote', 'Cotización Landed Cost'), ('validate_landed_cost', 'Validar Landed Cost'), ('epod_request', 'Solicitud ePOD'), ('api_error', 'Error de API'), ('system_action', 'Acción del sistema')], max_length=30)),
                ('status', models.CharField(choices=[('success', 'Exitoso'), ('error', 'Error'), ('warning', 'Advertencia'), ('info', 'Información')], default='success', max_length=10)),
                ('description', models.TextField(help_text='Descripción detallada de la acción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('resource_type', models.CharField(blank=True, help_text='Tipo de recurso afectado (ej: shipment, account)', max_length=50, null=True)),
                ('resource_id', models.CharField(blank=True, help_text='ID del recurso afectado', max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Datos adicionales de la actividad', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad de Usuario',
                'verbose_name_plural': 'Actividades de Usuario',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='dhl_api_use_user_id_7135b6_idx'), models.Index(fields=['action', '-created_at'], name='dhl_api_use_action_5a04d5_idx'), models.Index(fields=['status', '-created_at'], name='dhl_api_use_status_9edd24_idx')],
            },
        ),
    ]
