# Generated by Django 4.2.7 on 2025-08-04 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dhl_api', '0003_useractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Empresa')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='Estado/Provincia')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Código Postal')),
                ('country', models.CharField(max_length=2, verbose_name='País')),
                ('contact_type', models.CharField(choices=[('shipper', 'Remitente'), ('recipient', 'Destinatario'), ('both', 'Ambos')], default='both', max_length=10, verbose_name='Tipo de Contacto')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favorito')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Veces Usado')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Último Uso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-is_favorite', '-usage_count', '-last_used', '-created_at'],
                'unique_together': {('created_by', 'email', 'name')},
            },
        ),
    ]
