# Generated by Django 4.2.7 on 2025-08-04 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhl_api', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_type',
        ),
    ]
