# Generated by Django 4.2.7 on 2025-08-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhl_api', '0005_remove_contact_contact_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='Código de país ISO (2 letras)', max_length=2)),
                ('country_name', models.CharField(help_text='Nombre del país', max_length=100)),
                ('state_code', models.CharField(blank=True, help_text='Código del estado/provincia', max_length=10)),
                ('state_name', models.CharField(blank=True, help_text='Nombre del estado/provincia', max_length=100)),
                ('city_name', models.CharField(blank=True, help_text='Nombre de la ciudad', max_length=100)),
                ('service_area', models.CharField(help_text='Código del área de servicio DHL', max_length=10)),
                ('postal_code_from', models.CharField(blank=True, help_text='Código postal inicial', max_length=20)),
                ('postal_code_to', models.CharField(blank=True, help_text='Código postal final', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zona de Servicio',
                'verbose_name_plural': 'Zonas de Servicio',
                'indexes': [models.Index(fields=['country_code'], name='dhl_api_ser_country_e48a62_idx'), models.Index(fields=['country_code', 'state_code'], name='dhl_api_ser_country_c95143_idx'), models.Index(fields=['country_code', 'city_name'], name='dhl_api_ser_country_64d696_idx'), models.Index(fields=['service_area'], name='dhl_api_ser_service_dc07b7_idx')],
                'unique_together': {('country_code', 'state_code', 'city_name', 'postal_code_from', 'postal_code_to')},
            },
        ),
    ]
