# Generated by Django 4.2.7 on 2025-08-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhl_api', '0006_servicezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAreaCityMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='Código de país ISO (2 letras)', max_length=2)),
                ('state_code', models.CharField(blank=True, help_text='Código de estado/provincia (opcional)', max_length=10)),
                ('service_area', models.CharField(help_text='Código de área de servicio DHL (ej: YHM)', max_length=10)),
                ('city_name', models.CharField(help_text='Nombre base de ciudad (ej: Richmond Hill)', max_length=120)),
                ('display_name', models.CharField(help_text='Nombre final a mostrar (ej: Richmond Hill L4B 1B1)', max_length=180)),
                ('postal_code_from', models.CharField(blank=True, max_length=20)),
                ('postal_code_to', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas o fuente del mapeo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mapa Área de Servicio-Ciudad',
                'verbose_name_plural': 'Mapas Área de Servicio-Ciudad',
                'indexes': [models.Index(fields=['country_code', 'service_area'], name='dhl_api_ser_country_000a81_idx'), models.Index(fields=['country_code', 'state_code', 'service_area'], name='dhl_api_ser_country_81062b_idx')],
                'unique_together': {('country_code', 'state_code', 'service_area', 'postal_code_from', 'postal_code_to')},
            },
        ),
    ]
