# Generated by Django 4.2.7 on 2025-08-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhl_api', '0008_countryiso'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='countryiso',
            new_name='dhl_api_cou_code_cea843_idx',
            old_name='dhl_api_cou_code_idx',
        ),
        migrations.AlterField(
            model_name='countryiso',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='serviceareacitymap',
            index=models.Index(fields=['country_code', 'city_name'], name='dhl_api_ser_country_26132f_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceareacitymap',
            index=models.Index(fields=['country_code', 'state_code', 'city_name'], name='dhl_api_ser_country_557c14_idx'),
        ),
    ]
