# Configuración para Render Free Tier
services:
  - type: web
    name: dhl-api-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.render.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 60 --max-requests 200 --worker-class sync --preload dhl_project.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"
      - key: DHL_USERNAME
        sync: false  # Configurar manualmente en el dashboard
      - key: DHL_PASSWORD
        sync: false  # Configurar manualmente en el dashboard
      - key: DHL_BASE_URL
        value: "https://express.api.dhl.com"
      - key: DHL_ENVIRONMENT
        value: "production"
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      - key: DISABLE_COLLECTSTATIC
        value: "1"
    healthCheckPath: /api/health/
    
  # Frontend como sitio estático separado (recomendado para Free Tier)
  - type: static
    name: dhl-frontend
    buildCommand: |
      cd frontend
      npm ci
      npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: "https://dhl-api-backend.onrender.com/api"
      - key: REACT_APP_BACKEND_URL
        value: "https://dhl-api-backend.onrender.com/api"
      - key: REACT_APP_ENVIRONMENT
        value: "production"
      - key: GENERATE_SOURCEMAP
        value: "false"
