services:
  - type: web
<<<<<<< HEAD
    name: dhl-api-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.render.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 60 --max-requests 200 --worker-class sync --preload dhl_project.wsgi:application
=======
    name: dhl-backend
    env: docker
    dockerfilePath: ./Dockerfile
>>>>>>> 4ea3d89a1b6333578a0d73561ee8faa9091c3529
    envVars:
      - key: PORT
        value: 10000
      - key: DEBUG
        value: False
